version: '3.8'

services:
  api:
    build: .
    command:
      [
        "uvicorn",
        "server.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--workers",
        "4"
      ]
    container_name: vin-app
    restart: on-failure
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
